version: 0.0.1

versions:
  jquery: 1.8.1
  angular: 1.0.1
  require: 2.0.6
  modernizr: 2.6.2
  bootstrap: 2.1.0
  less: 1.3.0
  noty: 2.0.3

debug: true
minify: false

profiles:
  development:
    base_url: //localhost:4242
    api_http_url: //localhost:8080/jege-service/api/1
    api_resource_url: //localhost:port/jege-service/api/1
    api_resource_port: 8080
  developmentRemote:
    base_url: //localhost:4242
    api_http_url: //service-jege.rhcloud.com/api/1
    api_resource_url: //service-jege.rhcloud.com:port/api/1
    api_resource_port: 80
  staging:
    base_url: //jege.github.com/jege-angular
    api_http_url: //service-jege.rhcloud.com/api/1
    api_resource_url: //service-jege.rhcloud.com:port/api/1
    api_resource_port: 80
    debug: false
    deploy:
      host: github_pages 
  production:
    base_url: //jege.github.com/jege-angular
    api_http_url: //service-jege.rhcloud.com/api/1
    api_resource_url: //service-jege.rhcloud.com:port/api/1
    api_resource_port: 80
    debug: false
    minify: true
    