version: 0.0.1
jquery_version: 1.8.1
angular_version: 1.0.1

profiles:
  development:
    base_url: //localhost:4242
    api_http_url: //localhost:8080/jege-service/api/1
    api_resource_url: //localhost:port/jege-service/api/1
    api_resource_port: 8080
  staging:
    base_url: //jege.github.com/jege-angular
    api_http_url: //service-jege.rhcloud.com/api/1
    api_resource_url: //service-jege.rhcloud.com:port/api/1
    api_resource_port: 80
    deploy:
      host: github_pages 
  production:
    base_url: //jege.github.com/jege-angular
    api_http_url: //service-jege.rhcloud.com/api/1
    api_resource_url: //service-jege.rhcloud.com:port/api/1
    api_resource_port: 80
    